### ISSUE TITLE
Call to a member function toHex() on array

### ISSUE THREAD

**Issue by thsantac** [drlecks/Simple-Web3-Php#3]
Hi,

When calling $sweb3->send($sendParams), I get this error :

Fatal error: Uncaught Error: Call to a member function toHex() on array in /var/www/vhosts/hexakrown.io/httpdocs/vendor/drlecks/simple-web3-php/Core/Utils.php:98 Stack trace: #0 /var/www/vhosts/hexakrown.io/httpdocs/vendor/drlecks/simple-web3-php/Core/Utils.php(195): SWeb3\Utils::toHex() #1 /var/www/vhosts/hexakrown.io/httpdocs/vendor/drlecks/simple-web3-php/Core/SWeb3.php(131): SWeb3\Utils::forceAllNumbersHex() #2 /var/www/vhosts/hexakrown.io/httpdocs/api/INFURA/sendRawTransaction.php(388): SWeb3\SWeb3->send() #3 /var/www/vhosts/hexakrown.io/httpdocs/api/INFURA/sendRawTransaction.php(176): SWeb3\SendETH() #4 {main} thrown in /var/www/vhosts/hexakrown.io/httpdocs/vendor/drlecks/simple-web3-php/Core/Utils.php on line 98

Here is my code :

function SendETH($sweb3, $to, $amount)
{
    //send 0.001 eth to 0x3Fc47d792BD1B0f423B0e850F4E2AD172d408447
    // 0,015 000 000 000 000 000 want 1 000 000 000 000 000 000
    //estimate gas cost
    //if you don't provide explicit gas price, the system will update current gas price from the net (call)
    $sendParams = [ 
        'from' => $sweb3->personal->address,
        'to' => $to, 
        'value' => $amount      // Already with 18 décimals
    ]; 

    //get function estimateGas
    /*$gasEstimateResult = $sweb3->call('eth_estimateGas', [$sendParams]);

    if(!isset($gasEstimateResult->result))
        throw new Exception('SendETH - GAS estimation error: ' . json_encode($gasEstimateResult));   

    $gasEstimate = $sweb3->utils->hexToDec($gasEstimateResult->result);*/
    
    $gasEstimate = 39000000;
 
    //prepare sending
    $sendParams['nonce'] = $sweb3->personal->getNonce(); 
    $sendParams['gasLimit'] = $gasEstimate;

    $result = $sweb3->send($sendParams); 
    return json_encode($result);
}

I have commented gasEstimation because I got this error too.

It looks like in Utils.php the bn() function returns an array in place of a number.

Any suggestion ?

Thanks.

**Comment by drlecks** [comment]
Hi!

I've tried your function in several branch points (latest master, latest v0.9, tag v0.8) and everything seems to work as expected.

- What branch / commit are you trying this at?
- What value are you exactly passing to the $amount parameter? Can you show how do you call the SendETH(...) function?

As an example, I tried this 3 different amount values and all gave me the correct hex results (the fist 2 are the best approaches):

```
//0.01 ether -> 1000000000000000 wei 
$amount = $sweb3->utils->toWei('0.001', 'ether');   
$amount = '1000000000000000';   
$amount = 1000000000000000;   
```

**Comment by thsantac** [comment]
Hi, 

I have fixed the issue by passing new BigNumber($amount) to the sendETH() function instead of just $amount. 

I have now no more errors in $sweb3->send($sendParams) but I do not see the transaction on etherscan for the « to » address, don’t know why, investigating…

Thanks.

Cordialement.
Bonne journée.

Thierry Santacana - 0630927608
***@***.***

**Comment by drlecks** [comment]
> I have now no more errors in $sweb3->send($sendParams) but I do not see the transaction on etherscan for the « to » address, don’t know why, investigating…

You won't see the transaction on the sending/receiving addresses until it is accepted (not pending state). Best way to see if the tx is successfully sent is to track the transaction hash returned by $sweb3->send(...). Confirmation times on testnets are very volatile.

Defining a good gas price is important too if you want to see the results fast (estimateGas makes a good work with that).

**Comment by thsantac** [comment]
I have tried calling estimateGas but I’ve got : « invalid argument 0: json: cannot unmarshal hex string 0x into Go struct field TransactionArgs.value of type hexutil.Big » 

Have you already encountered this issue ?

Cordialement.
Bonne journée.

Thierry Santacana - 0630927608
***@***.***

**Comment by drlecks** [comment]
This is a RPC error response. This is telling that the transaction parameters are not well formatted.

 `struct field TransactionArgs.value` (value) is the problem, so we still have problems with the `$amount` var. For some reason forceAllNumbersHex is not converting the BigNumber or it is just not adding '0x'.

Yet again, if I knew the branch/commit that you are using, it would help. Also the exact amount you are sending to SendETH(). Remember that "amount" should be a wei number as string with only digits; no symbols, no comas, no dots...

BTW, does the default SendETH() (in example.send.php) work as expected on your setup?

**Comment by thsantac** [comment]
So, I have uncommented the eth_estimategas call.

The problem comes from what I send to SendEth() :

2022-07-29 10:01:59 ==> SendETH - sendParams : Array
(
    [from] => 0x89d63c03f276c88ec8bd45a395360bff207c5xxx
    [to] => 0x0f5afc66fc03618b17fe25b20ff0de2c1c926xxx
    [value] => phpseclib\Math\BigInteger Object
        (
            [value] => 0x
            [engine] => gmp
        )

    [gasPrice] => phpseclib\Math\BigInteger Object
        (
            [value] => 0x
            [engine] => gmp
        )

)

value and gasPrice comes from : $result         = SendETH($sweb3, $toWallet, new BigNumber($amount), new BigNumber($fees));
with $amount = 0.0001 and $fees = 0.0005.

I guess I have to do that before calling SendETH :

$decimals = 18;
$amount   = $amount * (10 ** $decimals);
$fees   = $fees * (10 ** $decimals);

Is that right?

Thanks a lot.

Cordialement.
Bonne journée.

Thierry Santacana - 0630927608
***@***.***

**Comment by drlecks** [comment]
Them problem comes from the decimals transformation. The ethereum environment does not handle decimal types (float/double). And PHP does not support big numbers by default. 

This code:
``` php
$amount = 0.0001;
$decimals = 18;
$amount   = $amount * (10 ** $decimals); 
var_dump($amount); 
```

Will output a wrong amount:
`float(1.0E+14)`

The correct way to make the transformation is:
``` php
$amount = '0.0001';
$amount_wei = Utils::toWei($amount, 'ether');  
```

Where amount will be: 
`BigNumber "0x5af3107a4000"` 

(You can "pretty print" BigNumbers with `$big_number_amount->toString();`)
`string(15) "100000000000000"`

**Comment by thsantac** [comment]
So, to be clear :

$amount = 0.0001;
$amount_wei = Utils::toWei($amount, 'ether');
$fees = 0.0005;
$fees_wei = Utils::toWei($fees, 'ether');
$result         = SendETH($sweb3, $toWallet, new BigNumber($amount_wei), new BigNumber($fees_wei));

If I do not transform $amount in a BigNumber instance, then I will have an error (the one I posted on GitHub).

Ok for you?

Cordialement.
Bonne journée.

Thierry Santacana - 0630927608
***@***.***

**Comment by drlecks** [comment]
> $amount = 0.0001;
> $amount_wei = Utils::toWei($amount, 'ether');

The above code will still be a problem. Note the quotes on the code example I shared previously:
``` php
$amount = '0.0001';
$amount_wei = Utils::toWei($amount, 'ether');  
```

Amount must be an **string** before converting it to wei. You are defining amount as a double. and won't be supported.

**Comment by thsantac** [comment]
So, with :

$amount         = strval($amount);
$amount_wei     = Utils::toWei($amount, 'ether');
$result         = SendETH($sweb3, $toWallet, $amount_wei);

No more gasPrice in $sendParams.

==> {"success":true,"error":""}

2022-07-29 12:41:34 ==> SWeb3 - send - nonce=0x1, gasPrice=0x36498a891, gasLimit=0x5208, to=0x0f5afc66fc03618b17fe25b20ff0de2c1c92xxxx, value=0x5af3107a4000, data=, chainId=0x1
2022-07-29 12:41:34 ==> SendETH - result: Array
(
    [jsonrpc] => 2.0
    [id] => 0
    [result] => 0x143c71307e8846472a74b49a64270767b79a8c71b03facad884cd78bc698861f
)

And the transaction hash exists on EtherScan !!!

:-)

Again, thanks a lot for your great help !

Cordialement.
Bonne journée.

Thierry Santacana - 0630927608
***@***.***

**Comment by thsantac** [comment]
And I forgot to say : I use the latest commit :-)

Cordialement.
Bonne journée.

Thierry Santacana - 0630927608
***@***.***
